cc_test(
    name="binary_indexed_tree_test",
    srcs=[
        "binary_indexed_tree_test.cc",
        "binary_indexed_tree.h",
    ],
    deps=["@googletest//:gtest_main"],
)

cc_test(
    name="splay_tree_test",
    srcs=[
        "splay_tree_test.cc",
        "splay_tree.h",
    ],
    deps=["@googletest//:gtest_main"],
)